# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='platform_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('stores', models.CharField(max_length=100)),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('url_openfoodfact', models.URLField(max_length=100)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Substitute_Platform.Categories')),
            ],
        ),
        migrations.AddField(
            model_name='platform_user',
            name='substituent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_substituent', to='Substitute_Platform.Products'),
        ),
        migrations.AddField(
            model_name='platform_user',
            name='substituted_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_substituted', to='Substitute_Platform.Products'),
        ),
        migrations.AddField(
            model_name='platform_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
