# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Substitute_Platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Substitute_Platform.Categories'),
        ),
    ]
