# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Substitute_Platform', '0002_auto_20190130_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(to='Substitute_Platform.Categories'),
        ),
    ]
