# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Substitute_Platform', '0003_auto_20190131_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
