# Generated by Django 2.1.5 on 2019-02-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Substitute_Platform', '0005_auto_20190211_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(default='none', max_length=100),
        ),
    ]
