# Generated by Django 2.1.5 on 2019-02-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Substitute_Platform', '0006_products_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform_user',
            name='substituent_product',
        ),
        migrations.AddField(
            model_name='platform_user',
            name='substituent_product',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='produit_substituant', to='Substitute_Platform.Products'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='platform_user',
            name='substituted_product',
        ),
        migrations.AddField(
            model_name='platform_user',
            name='substituted_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produit_substite', to='Substitute_Platform.Products'),
        ),
    ]
