# Generated by Django 2.1.5 on 2019-02-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Substitute_Platform', '0008_auto_20190225_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_user',
            name='substituent_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='produit_substituant', to='Substitute_Platform.Products'),
        ),
        migrations.AlterField(
            model_name='platform_user',
            name='substituted_product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit_substite', to='Substitute_Platform.Products'),
        ),
    ]
