# Generated by Django 2.2 on 2019-04-04 08:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Substitute_Platform', '0014_auto_20190319_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='platform_user',
            unique_together={('user', 'substituted_product', 'substituent_product')},
        ),
    ]
